In [ ]:
import tensorflow as tb

In [ ]:
tensor_zerodimnesion = tb.constant(4)    # .constant creates_tensor_whose_val(immutable)
print(tensor_zerodimnesion)


tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_dimen = tb.constant([2,0,-3,8 , 226.])      # also_datatype_changes
print(tensor_one_dimen)

tf.Tensor([  2.   0.  -3.   8. 226.], shape=(5,), dtype=float32)


In [ ]:
tensor_two_dimen = tb.constant([
    [0,1,2],[5,61,4] ,
      [5,2,4],


])
print(tensor_two_dimen)

tf.Tensor(
[[ 0  1  2]
 [ 5 61  4]
 [ 5  2  4]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_dimen = tb.constant([
     [
      [0,1,2],[5,61,4] ,
      [5,2,4],
     ]  ,
#[
   #[4,2,1],[8,1,0] ,[0,6,3]]

])
print(tensor_three_dimen)

tf.Tensor(
[[[ 0  1  2]
  [ 5 61  4]
  [ 5  2  4]]], shape=(1, 3, 3), dtype=int32)


In [ ]:
print(tensor_three_dimen.shape)           # slight diff in function
print(tb.shape  (tensor_three_dimen) )

(1, 3, 3)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
print(tensor_two_dimen.ndim)

2


In [ ]:
tensor_four_dimension = tb.constant([[
[
[1,0,8] ] , [
    [5,1,9]
]



]])
print(tensor_four_dimension)

tf.Tensor(
[[[[1 0 8]]

  [[5 1 9]]]], shape=(1, 2, 1, 3), dtype=int32)


CAST METHOD

In [ ]:
tensor_one_dimen = tb.constant([2,0,-3,8 , 226.] , dtype=tb.float32)

cast_tensor = tb.cast(tensor_one_dimen , dtype=tb.int32)          # creates_tensor_tonew_type
cast_tense = tb.cast(tensor_one_dimen , dtype=tb.bool)

print(tensor_one_dimen)
print(cast_tensor)
print(cast_tense)

tf.Tensor([  2.   0.  -3.   8. 226.], shape=(5,), dtype=float32)
tf.Tensor([  2   0  -3   8 226], shape=(5,), dtype=int32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [ ]:
import numpy as np
nop = np.array([1,2,5])
print(nop)

[1 2 5]


CONVERTING TO TENSOR


In [ ]:
top = tb.convert_to_tensor(nop, dtype=tb.float32)
print(top)

tf.Tensor([1. 2. 5.], shape=(3,), dtype=float32)


tb.eye METHOD

In [ ]:
eio = tb.eye(                               # IDENTity matrix
    num_rows=5,
    num_columns=None,
            batch_shape=[2],
    dtype=tb.dtypes.float32,
    name=None
)
print(3*eio)

tf.Tensor(
[[[3. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 3. 0. 0.]
  [0. 0. 0. 3. 0.]
  [0. 0. 0. 0. 3.]]

 [[3. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 3. 0. 0.]
  [0. 0. 0. 3. 0.]
  [0. 0. 0. 0. 3.]]], shape=(2, 5, 5), dtype=float32)


tb.zeros and tf.ones METHOD

In [ ]:
# creating tensors which are all_set to zero

In [ ]:
zerop = tb.zeros([4,3] , dtype=tb.float16)
print(zerop)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float16)


tf.rank SAME AS The order , degree , ndim

In [ ]:
print(tb.rank(zerop))             # always returns tensor with type int32

tf.Tensor(2, shape=(), dtype=int32)


tf.random.normal o/p's random value from normal distribution

In [ ]:
print(  tb.random.normal([4,2] ,mean=80, stddev =1.0 ,dtype = tb.float16)    )     # by default dtypefloatd

tf.Tensor(
[[80.6  79.75]
 [79.4  80.75]
 [78.7  79.5 ]
 [80.75 80.8 ]], shape=(4, 2), dtype=float16)


tf.random.uniform o/p's random value from uniform distribution

In [ ]:
tb.random.uniform( [2,2] ,minval=0 ,maxval=5)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.091023  , 0.88374615],
       [4.2071447 , 3.3095348 ]], dtype=float32)>

TENSOR INDEXING

In [ ]:
ind = tb.constant( [1,4,5,6,9])
print(ind[1:4])          #print(ind[4])

tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [ ]:
tb.range(2,11+1)     # to include thelast_onealso

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [ ]:
ind[0:5:2]        #diff of two_in_tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 5, 9], dtype=int32)>

In [ ]:
# FOR 2D TENSORS i.e rows:columns

two_d = tb.constant([
    [1,4,6]
 ,[4,4,8], [4,79,51]  , [14,58,93]

])
print(two_d)

tf.Tensor(
[[ 1  4  6]
 [ 4  4  8]
 [ 4 79 51]
 [14 58 93]], shape=(4, 3), dtype=int32)


In [ ]:
print(two_d[ 0:3+1 , 0:2] )
two_d[ ... , 2]

tf.Tensor(
[[ 1  4]
 [ 4  4]
 [ 4 79]
 [14 58]], shape=(4, 2), dtype=int32)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 51, 93], dtype=int32)>

In [ ]:
three_d = tb.constant([
    [
        [4,5,6],[4,8,0]
    ],
    [ [0,1,9] ,[7,3,8] ]

])
print(three_d.shape)


(2, 2, 3)


In [ ]:
three_d[-1 , -1 , ...]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 3, 8], dtype=int32)>