In [2]:
import tensorflow as tk

PERFORMING MATHEMATICAL OPERATIONS

In [ ]:
# tf.math.abs METHOD  returns absolute_value of tensor

xy = tk.abs([2,1,-8,7])
print(xy)

tf.Tensor([2 1 8 7], shape=(4,), dtype=int32)


In [ ]:
# FOR COMPLEX NUMEBRS

xys = tk.abs([ [-2.5+1.2j]  ])
print(xys)


tf.Tensor([[2.77308492]], shape=(1, 1), dtype=float64)


In [ ]:
# checkingcross the answer using funct

tk.sqrt( (-2.5)**2 + (1.2)**2)

<tf.Tensor: shape=(), dtype=float32, numpy=2.773084878921509>

In [ ]:
# ADD OPERATION
y1 = [1,2,5,8]
y3 = 15
tk.add(y1,y3)

# OR THIS
y1=tk.constant( [1,2,5,8] )
y3 = tk.convert_to_tensor(y3)
print(y1+y3)
print(tk.multiply(y1,y3))              #this is not actual matmultiplication,this on place of index_itself


tf.Tensor([16 17 20 23], shape=(4,), dtype=int32)
tf.Tensor([ 15  30  75 120], shape=(4,), dtype=int32)


In [ ]:
y1=tk.constant( [1,2,5,8] )
y3 = tk.convert_to_tensor([15])         # size should beofbothsame/dimenson or error
y1+y3

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([16, 17, 20, 23], dtype=int32)>

In [ ]:
# argmax METHOD

y1=tk.constant( [1,2,5,8 ,154 ,28 ,56] )       #indexwith_largest_value

print(tk.math.argmin(y1))

tk.math.argmax(y1)



tf.Tensor(0, shape=(), dtype=int64)


<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
# POW METHOD

j1 =  tk.constant( [1,2,4,5,6] )
j2 = tk.constant( [ 4,6,9,3,10] )

tk.pow(j1,j2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([       1,       64,   262144,      125, 60466176], dtype=int32)>

In [ ]:
# math.reduce_mean calc. sum of elements_across dimensions , math.reduce_sum

j3 = tk.constant([
    [1,2,9] ,
     [4,0,9],
      [8,7,3]
])

print(tk.math.reduce_mean(j3 , axis=1) )

tk.math.reduce_sum(j3,axis=0)                  # axis=0 down and axis=1 across_the_line


tf.Tensor([4 4 6], shape=(3,), dtype=int32)


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([13,  9, 21], dtype=int32)>

In [ ]:
print ( tk.math.reduce_min(j3)  )              # it returns max_element and also the indexes
print( tk.math.top_k(j3,2))

tf.Tensor(0, shape=(), dtype=int32)
TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 2],
       [9, 4],
       [8, 7]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 0],
       [0, 1]], dtype=int32)>)


PERFORMING LINEAR ALGEBRAIC OPERATIONS

In [ ]:
# ON 2D(MATRIX)

g1 = tk.constant([[
  4,5,3] , [4,8,9]
])
print(g1).shape)
g2 = tk.constant([[
  1,9,0] , [1,8,0] ,[4,8,3]
])
print(g2.shape)


(2, 3)
(3, 3)


In [ ]:
tk.matmul(g1,g2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 21, 100,   9],
       [ 48, 172,  27]], dtype=int32)>

In [ ]:
g1@g2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 21, 100,   9],
       [ 48, 172,  27]], dtype=int32)>

In [ ]:
# here the cols becomes rows
print(tk.transpose(g1) )
g1                             # the shape changes

tf.Tensor(
[[4 4]
 [5 8]
 [3 9]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 3],
       [4, 8, 9]], dtype=int32)>

In [4]:
# ON 3D-MATRIX

k1 = tk.constant([
 [  [1,2] ,[4,5] , [6,7] ] ,         #here in3d matrix size should match_withother_one
 [  [4,5] ,[7,89],[4,9] ]               # 3*2

])
print(k1.shape)

k2 = tk.constant([
    [  [1,5] ,[4,4] ] ,                       #2*2
 [  [4,0] ,[94,1] ]

])

tk.matmul(k1,k2)


(2, 3, 2)


<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[   9,   13],
        [  24,   40],
        [  34,   58]],

       [[ 486,    5],
        [8394,   89],
        [ 862,    9]]], dtype=int32)>

In [ ]:
#cross product needing same size

s1 = tk.constant([[             #this is rowise product
  4,5,3] , [4,8,9],[1,2,5]
])

s2 = tk.constant([[
  1,9,0] , [1,8,0] ,[4,8,3]
])

tk.linalg.cross(s1,s2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-27,   3,  31],
       [-72,   9,  24],
       [-34,  17,   0]], dtype=int32)>

In [ ]:
# Inverse of matrix

s2 = tk.constant([[              #must beof float and comlpex_data_type
  1,9,0] , [1,8,0] ,[4,8,3]
]  , dtype=tk.float32)

tk.linalg.inv(s2)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-8.0000000e+00,  9.0000000e+00,  1.4901161e-08],
       [ 1.0000000e+00, -1.0000000e+00, -2.1287374e-09],
       [ 8.0000000e+00, -9.3333330e+00,  3.3333331e-01]], dtype=float32)>

In [ ]:
# a is a tensor
# s is a tensor of singular values
# u is a tensor of left singular vectors
# v is a tensor of right singular vectors     returns singular value_decompostition ofone_more_matrices

s ,u,v=  tk.linalg.svd(s2)
print(s,v)

tf.Tensor([14.967265   3.4608653  0.0579154], shape=(3,), dtype=float32) tf.Tensor(
[[ 0.23634711  0.6766912  -0.69730127]
 [ 0.9641298  -0.25254124  0.08171052]
 [ 0.12080454  0.6916009   0.7121055 ]], shape=(3, 3), dtype=float32)


In [6]:
# tf.einsum METHOD
import numpy as np

a=np.array([
    [4,5] , [9,6] , [1,2]
])
print(a.shape)
b=np.array([
    [4,5,9,6,0] , [9,6,1,4,0]
])
print(b.shape)

print('MATRIX C - ')
print(np.matmul(a,b))

(3, 2)
(2, 5)
MATRIX C - 
[[61 50 41 44  0]
 [90 81 87 78  0]
 [22 17 11 14  0]]


In [ ]:
print('einsum C -')
print(np.einsum('ij,jk->ik',a,b))         # the script must_ beinside the string

einsum C -
[[61 50 41 44  0]
 [90 81 87 78  0]
 [22 17 11 14  0]]


In [ ]:
print('TRANSPOSE OF MATRIX - ')
print(a.T)

# using ensum method to find transpose
print('ensum of a -')
print(np.einsum("ij->ji",a))            # for transpose

TRANSPOSE OF MATRIX - 
[[4 9 1]
 [5 6 2]]
ensum of a -
[[4 9 1]
 [5 6 2]]


In [9]:
f1 = np.array([
    [
        [1,4,2,1],[8,96,4,1],[0,5,6,7]
    ],
    [
        [1,3,7,1],[8,96,0,2],[0,4,3,8]

    ]
])
print(f1.shape)
f2=np.array([
 [[ 1,  2,  3,  4,  5],
  [ 6,  7,  8,  9, 10],
  [11, 12, 13, 14, 15],
  [16, 17, 18, 19, 20]],

 [[21, 22, 23, 24, 25],
  [26, 27, 28, 29, 30],
  [31, 32, 33, 34, 35],
  [36, 37, 38, 39, 40]]

])

print(f2.shape)
# normal_multipl
print( np.matmul(f1,f2) )

#using einsum

print('einsum c - ')
print(np.einsum("bij,bjk->bik",f1,f2))    #compare_the scriptwith_dimensions_tounderstand



(2, 3, 4)
(2, 4, 5)
[[[  63   71   79   87   95]
  [ 644  753  862  971 1080]
  [ 208  226  244  262  280]]

 [[ 352  364  376  388  400]
  [2736 2842 2948 3054 3160]
  [ 485  500  515  530  545]]]
einsum c - 
[[[  63   71   79   87   95]
  [ 644  753  862  971 1080]
  [ 208  226  244  262  280]]

 [[ 352  364  376  388  400]
  [2736 2842 2948 3054 3160]
  [ 485  500  515  530  545]]]


In [ ]:
# for sum
print(np.einsum("bij-> ",f1))

268
