tf.expand_dims returns a tensor with a length 1 axis inserted at index axis

In [2]:

import tensorflow as tg
f1 = tg.constant([
    [
        [1,4,2,1],[8,96,4,1],[0,5,6,7]
    ],
    [
        [1,3,7,1],[8,96,0,2],[0,4,3,8]

    ]
])

print(f1.shape)
print(f1)

(2, 3, 4)
tf.Tensor(
[[[ 1  4  2  1]
  [ 8 96  4  1]
  [ 0  5  6  7]]

 [[ 1  3  7  1]
  [ 8 96  0  2]
  [ 0  4  3  8]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
tg.expand_dims(f1,axis=1)           # u cansee how it inserts an extra 1dimension ,by seperating

<tf.Tensor: shape=(2, 1, 3, 4), dtype=int32, numpy=
array([[[[ 1,  4,  2,  1],
         [ 8, 96,  4,  1],
         [ 0,  5,  6,  7]]],


       [[[ 1,  3,  7,  1],
         [ 8, 96,  0,  2],
         [ 0,  4,  3,  8]]]], dtype=int32)>

In [ ]:
tg.expand_dims(f1,axis=3)        # for the last_one runned it and seeit_got_concentratedinto one

<tf.Tensor: shape=(2, 3, 4, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 4],
         [ 2],
         [ 1]],

        [[ 8],
         [96],
         [ 4],
         [ 1]],

        [[ 0],
         [ 5],
         [ 6],
         [ 7]]],


       [[[ 1],
         [ 3],
         [ 7],
         [ 1]],

        [[ 8],
         [96],
         [ 0],
         [ 2]],

        [[ 0],
         [ 4],
         [ 3],
         [ 8]]]], dtype=int32)>

squeeze Removes dimensions of size 1 from the shape of a tensor ,needs_tensor_of_size-1 for that particular shape

In [ ]:
f2=tg.constant([
    [[0,1,8,9,63,47,5123]]     # here at second axis there are 7i/p so cant be squeesed
    ])
print(f2)



tf.Tensor([[[   0    1    8    9   63   47 5123]]], shape=(1, 1, 7), dtype=int32)


In [ ]:
tg.squeeze(f2,axis=1)

<tf.Tensor: shape=(1, 7), dtype=int32, numpy=array([[   0,    1,    8,    9,   63,   47, 5123]], dtype=int32)>

In [ ]:
print(f1)

tf.Tensor(
[[[ 1  4  2  1]
  [ 8 96  4  1]
  [ 0  5  6  7]]

 [[ 1  3  7  1]
  [ 8 96  0  2]
  [ 0  4  3  8]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
# tf.reshape does not change the order of or the total number of elements in the tensor, and so it can reuse the underlying data buffer.
 # This makes it a fast operation independent of how big of a tensor it is operating on

In [4]:
f3= tg.constant([
    [[1,3,2] ,[4,1,8]
     ] , [ [4,1,2] , [4,5,8] ]
])
print(f3)

tf.Tensor(
[[[1 3 2]
  [4 1 8]]

 [[4 1 2]
  [4 5 8]]], shape=(2, 2, 3), dtype=int32)


In [5]:
print(tg.reshape(f3,[6,2]))         # can reshaped to  any but taking care of total_elements_tpresentin f3

tf.Tensor(
[[1 3]
 [2 4]
 [1 8]
 [4 1]
 [2 4]
 [5 8]], shape=(6, 2), dtype=int32)
