RAGGED TENSORS

In [1]:
import tensorflow as tb

In [ ]:
# h1 = tb.constant([
#     [1,2,3],[4,8,9],[4,5]      thiscan't_be conv_as itsinner_dimension_arenotof_equal_length
# ])

h1=([
  [4,2,3],[4,1],[0]

])
top = tb.ragged.constant(h1)
print(top.shape)
top


(3, None)


<tf.RaggedTensor [[4, 2, 3], [4, 1], [0]]>

In [ ]:
# RaggedTensor with rows partitioned by row_lengths

h2 = [4,5,6,1,21,15,47]
tb.RaggedTensor.from_row_lengths(h2,[4,2,0,1,0])       # returns  rank(dimen)+1

<tf.RaggedTensor [[4, 5, 6, 1], [21, 15], [], [47], []]>

In [6]:
h2 = [ [4,5,6,1,21,15,47],[1,4,5,7,8,5,7]]            # from_tensor expects only regular_matrix(dense matrix)not_irregular listortensor
tb.RaggedTensor.from_tensor(h2,[2,4])

<tf.RaggedTensor [[4, 5], [1, 4, 5, 7]]>

SPARSE TENSOR

In [ ]:
# tb.sparse.SparseTensor([[0,1,2],[0,1,1]], [15,45],[1,2,3])    only expects 2dlist/tensor
# tb.sparse.to_dense(tb.sparse.SparseTensor([[0,1,2],[0,1,1]], [15,45],[1,2,3]))

In [ ]:
got = tb.sparse.SparseTensor(indices=[[0,0],[1,0]] , values=[45,11] , dense_shape=[5,7])      #indices_should_beinsorted order
print(got)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 0]], shape=(2, 2), dtype=int64), values=tf.Tensor([45 11], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 7], shape=(2,), dtype=int64))


In [ ]:
tb.sparse.to_dense(got)

<tf.Tensor: shape=(5, 7), dtype=int32, numpy=
array([[45,  0,  0,  0,  0,  0,  0],
       [11,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]], dtype=int32)>

STRING TENSORS

In [ ]:
st = tb.constant([
    'Hey','Fabian yo',"nice"
])

In [ ]:
# Join method

tb.strings.join(st,separator=' ')                # Perform element-wise concatenation of a list of string tensors.

<tf.Tensor: shape=(), dtype=string, numpy=b'Hey Fabian yo nice'>

In [ ]:
tb.strings.join(st,separator='-_-')

<tf.Tensor: shape=(), dtype=string, numpy=b'Hey-_-Fabian yo-_-nice'>

In [ ]:
tb.strings.lower(st)

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'hey', b'fabian yo', b'nice'], dtype=object)>

In [ ]:
# VARIABLES TENSORS

In [ ]:
tb.Variable(h2)


<tf.Variable 'Variable:0' shape=(2, 7) dtype=int32, numpy=
array([[ 4,  5,  6,  1, 21, 15, 47],
       [ 1,  4,  5,  7,  8,  5,  7]], dtype=int32)>

In [8]:
ho = tb.Variable(h2,name='any')
print(ho)

<tf.Variable 'any:0' shape=(2, 7) dtype=int32, numpy=
array([[ 4,  5,  6,  1, 21, 15, 47],
       [ 1,  4,  5,  7,  8,  5,  7]], dtype=int32)>


In [9]:
ho.assign_sub([[ 1,  4,  5,  7,  8,  5,  7],[4,  5,  6,  1, 21, 15, 47]])

<tf.Variable 'UnreadVariable' shape=(2, 7) dtype=int32, numpy=
array([[  3,   1,   1,  -6,  13,  10,  40],
       [ -3,  -1,  -1,   6, -13, -10, -40]], dtype=int32)>